name: deploy

on:
  push:
    branch:
      - master

jobs:
  build:
    name: Deploy Flask App
    env:
        SECRET_VALUE: '${{ secrets.SECRET_VALUE }}'
    runs-on: self-hosted
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
      
    - name: Build and Run Docker
      run: |
        docker build --build-arg SECRET_VALUE=$SECRET_VALUE -t tutorial/1-flask-deployment .
        docker run -dp 5001:5001 tutorial/1-flask-deployment