name: deploy

on:
  push:
    branch:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build and Run Docker
      run: docker build -t tutorial/1-flask-deployment . && docker run -dp 5001:5001 tutorial/1-flask-deployment
      env: # Or as an environment variable
        super_secret: ${{ secrets.SECRET_VALUE }}    
    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.SECRET_VALUE }}
      run: |
        example-command "$SUPER_SECRET"

