name: test

on:
  push:
    branch:
      - develop

jobs:
  test:
    name: Unit Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: set pythonpath
        run: |
          echo "PYTHONPATH=mlprepare" >> $GITHUB_WORKSPACE
      - name: Run tests
        run: pytest tests/